### ISSUE TITLE
Update to cinnamon 2.4 has made notes inaccessable

### ISSUE THREAD

**Issue by bainzo** [lestcape/Sticky-Notes#19]
After updating to Cinnamon 2.4 my notes no longer appear in Sticky Notes (v0.9.3-beta). 

I will update my version of Sticky Notes as you have suggested here, <http://segfault.linuxmint.com/2014/11/cinnamon-2-4/#comment-156492>, however before I upgrade I was wondering if it will be possible to recover my old notes or are they lost?

Thank you for writing sticky notes!

**Comment by lestcape** [comment]
There are 3 enhanced procedures to not lose the notes now:

- If you edit the note you can use CTRL+Z (undo function), also the redo function (CTRL+Y) is available.
- If you delete the note, now the file will be send to the trash system, instead of a permanently delete, could recover from the nemo trash folder and will automatically loaded when will recovered. If you want a permanently delete, you can change this in the settings.
- You can export all your notes to one file that will be write in your desktop folder from the settings or the right click menu.

So, actually will be really difficult lose your notes.
