### ISSUE TITLE
Deleted text restored after reboot

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [lestcape/Sticky-Notes#22]
Dear developer(s)

I really appreciate this piece of software; it's great - thanks for writing it.

A small problem: seemingly when I delete the text of a note, but retain the note (I like to leave my themed bit of notepaper where it is, for use later), after a reboot the same text (e.g. 'Do external backup;) re-appears. Any advice? Thanks.

**Comment by lestcape** [comment]
Hi, thanks.

Notes are on ~/.local/share/notes to prevent any problem do the backup manually.

I see what you say about delete the notes. Yes, same text appear, is difficult fix this, because i can not allow an empty note and also delete an empty note without explicit user action is not a good desition, I think. I do not allow empty notes, because is not usefull to user and this will create another instance of the desklet (loss resources for nothing). The note are create only when has a text, otherwise not. Do you have any idea what will be a good behavior to do when this happen?

You can find the current notepaper on ~/.local/share/cinnamon/desklets/stickyNotes@lestcape/stripe, is really a little difficult write a new one and is not allowed all possibilities. To create a new one you need to override the a currently one. If you finally do that, i can create then the spaces to be included on the original code if you want to share your creation...

Regards and thanks.

**Comment by ACinnamonUserInUK** [comment]
Sorry for the very late reply.

I am afraid that I have some trouble understanding you. Therefore, I do not know quite how to answer your question. The question of yours that I have in mind is as follows.

> Do you have any idea what will be a good behavior to do when this happen?

Let me _try_ to answer, though

I think that _either_
(1) the user should be prevented from leaving a note totally empty
_or_
(2) your software should be able to cope with there been an empty note. Perhaps you could (i) insert a space into the note, or (ii) insert the text '<Blank>.

**Comment by lestcape** [comment]
Hi.
Sorry, I really do not speak English natively, just i try...

(1 and 2 are for me the same) I don't know why will be important leaving a note totally empty or not.

I try to preserved the not all that i can, for example, if you leave the note complete empty, will be restore when you restart cinnamon or when you swap from multi-instance to one instance. This is because you don't explicit delete it. If you want to delete a note use the delete bottom instead. I don't see then this as a bug and maybe it's for you a bug, could be...

Please see what other user want : https://github.com/lestcape/Sticky-Notes/issues/24

I can provide you also externals links where user lost his notes... What you propose could be another way of lost the notes accidentally...
