### ISSUE TITLE
CTRL+Z support

### ISSUE THREAD

**Issue by pdefreitas** [lestcape/Sticky-Notes#24]
CTRL+Z support would be nice. I've accidently deleted the whole content of a note I had and I'm sure this happends a lot to the users. It would be an good enhancement.

**Comment by lestcape** [comment]
You are really right, i need to read the standards, but could you first recommend this to be included on cinnamon as a characteristics of the entries? Will be useful for several things, and duplicate the enforcer is not useful. If this get a negative, i will do that only for sticky notes.

Thanks.

**Comment by samcunliffe** [comment]
+1

I have accidentally deleted the whole content of a note several times :-(  
 (for me, it is by hitting 'escape' whilst typing.... because I have vim muscle-memory).

So would also appreciate an "undo" feature... @pdefreitas : did you make a cinnamon request? Where  can I add a +1? For my own personal problem, somehow changing the behaviour that the Esc key deletes the whole note would be equally appreciated.

**Comment by lestcape** [comment]
@samcunliffe i relly don't know how relate the undo with preserve the notes. If you delete the note also you delete the stack of last accions, so you can not recover the note with undo after delete it.

**Comment by pdefreitas** [comment]
@samcunliffe I did not report this since I've stopped using that kind of sticky notes and adopted another method to guide my notes (a kanboard). I suggest you to report it.

**Comment by rustyworks** [comment]
+1 I also have same issue with samcunliffe, I accidentally press esc after finishing typing

**Comment by lestcape** [comment]
If you hit scape, you will lost the last change, and apparently the note, but for example if you restart cinnamon after this the note will appear again. There are others way to recover the note, but this have not scene, this behaviour is clear wrong, as you commented.

Now escape key only will release the focus and this involved save the note that also involved lost the original text. Please see this is again the normal behaviour of escape key.
https://github.com/lestcape/Sticky-Notes/commit/dcda0544b84c300bb005b378f35e8d83d82ba233

**Comment by lestcape** [comment]
There are another solution and this is when you hit Escape key, then recover the original text of the note that is saved. this behaviour has have more scene to me, but any way you will lost the last change.

**Comment by rustyworks** [comment]
> Now escape key only will release the focus and this involved save the note that also involved lost the original text. Please see this is again the normal behaviour of escape key.
dcda054

This solve the problem !! Thanks !!

**Comment by lestcape** [comment]
Was added CTRL+Y(redo)  CTRL+Z(undo) support(https://github.com/lestcape/Sticky-Notes/commit/f0d50151016f3d7a75c85b797896adf3a228f3f9)

Direct download:
https://github.com/lestcape/Sticky-Notes/archive/master.zip

Please report any problem about this feature in a new thread.

**Comment by lestcape** [comment]
@samcunliffe : There are 3 enhanced procedures to not lose the notes now:

- If you edit the note you can use CTRL+Z (undo function), also the redo function (CTRL+Y) is available.
- If you delete the note, now the file will be send to the trash system, instead of a permanently delete, could recover from the nemo trash folder and will automatically loaded when will recovered. If you want a permanently delete, you can change this in the settings.
- You can export all your notes to one file that will be write in your desktop folder from the settings or the right click menu.

So, actually will be really difficult lose your notes.
